import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'todo-input',
  template: `
  <input [value]="title" (keyup.enter)="changeTitle($event.target.value)">
  <button (click)="changeTitle('Button Clicked!')">
    Save
  </button>
  <p>The title is: {{ title }}</p>
`,
  styleUrls: ['./input.component.css']
})
export class InputComponent implements OnInit {

  title: string;

  constructor() {
    this.changeTitle('I love Angular');
   }

  ngOnInit() {
    this.generateTitle();
  }

  changeTitle(newTitle: string): string {
    this.title = newTitle;
    return this.title;
  }

  private generateTitle(): string {
    return 'This title was generated by a method.';
  }
}
